development:
  url: ${DATABASE_URL}
  migrations_dir: ${MIGRATIONS_DIR}

production:
  url: ${DATABASE_URL}
  migrations_dir: ${MIGRATIONS_DIR}

test:
  url: ${DATABASE_URL}
  migrations_dir: ${MIGRATIONS_DIR}